import type { Metadata } from 'next'
import './globals.css'
import { caveat, zenkaku } from '@/libs/font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={`${caveat.variable} ${zenkaku.variable}  flex min-h-screen flex-col antialiased`}>
        {children}
      </body>
    </html>
  )
}
